version: '2'
services:
    hakoblankapp-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/hakoBlankApp/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=hakoBlankApp
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
